# Generated by Django 3.2.6 on 2021-08-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
