# Generated by Django 3.2.6 on 2021-08-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_site', '0002_imagefile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
