# Generated by Django 3.2.6 on 2021-08-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_site', '0003_alter_imagefile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='filename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
