# Generated by Django 3.2.6 on 2021-08-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_site', '0005_remove_imagefile_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagelabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagename', models.CharField(blank=True, max_length=100, null=True)),
                ('x1', models.CharField(blank=True, max_length=10, null=True)),
                ('y1', models.CharField(blank=True, max_length=10, null=True)),
                ('x2', models.CharField(blank=True, max_length=10, null=True)),
                ('y2', models.CharField(blank=True, max_length=10, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
