# Generated by Django 3.2.6 on 2021-08-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_site', '0006_imagelabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
