# Generated by Django 3.2.6 on 2021-08-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_site', '0007_imagefile_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ueser', models.CharField(blank=True, max_length=100, null=True)),
                ('pwd', models.CharField(blank=True, max_length=100, null=True)),
                ('authority', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='imagelabel',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
