# Generated by Django 3.2.6 on 2021-08-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_site', '0009_auto_20210825_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userimgae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('imagename', models.CharField(blank=True, max_length=100, null=True)),
                ('labelnote', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
