# Generated by Django 3.2.6 on 2021-08-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_site', '0010_userimgae'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagefile',
            old_name='file',
            new_name='imagename',
        ),
        migrations.RenameField(
            model_name='imagefile',
            old_name='label',
            new_name='labelnote',
        ),
    ]
