# Generated by Django 3.2.6 on 2021-08-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_site', '0011_auto_20210826_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelabel',
            name='warn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
